version: '2.2'
services:
  mt-nginx-build:
    image: nginx_monitor_prod
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env-prod.env
    ports:
      - 8080:8080
    volumes:
      - /home/ubuntu/logs:/mnt/logs
