version: '2'
services:
  mt-nginx:
    image: nginx_monitor_prod
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env-prod.env
    ports:
      - 8001:8080
    volumes:
      - /home/ubuntu/logs:/mnt/logs
